version: '3.1'
services:
  db:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres
    ports: 
      - 9432:5432
    restart: always
    volumes:
      - "${PWD}:/docker-entrypoint-initdb.d"
